title: rkoopmann
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rkoopmann.com" # the base hostname & protocol for your site, e.g. http://example.com
mastadon_username: "@rkoopmann@hachyderm.io"
github_username: rkoopmann
author: Richard Koopmann

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/pdf"
    values:
      pdf: true
# get a listing of all pdfs, for example
# {% assign image_files = site.static_files | where: "pdf", true %}
# {% for myimage in image_files %}
#   {{ myimage.path }}
# {% endfor %}

collections:
  events:
    output: true
    permalink: /event/:year-:month-:day/
  posts:
    output: true
    permalink: /post/:year-:month-:day/
#   tags:
#     output: true

markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: :categories/:title
