id: 1618131760
name:
  - short: do over
  - full: do over — text permutations
link:
  - www: "https://do-over.app"
  - appstore: "https://apps.apple.com/us/app/do-over-text-permutations/id1618131760"
  - macappstore: "https://apps.apple.com/us/app/do-over-text-permutations/id1618131760"
